The exact location of departure is not mentioned in the emails which prompted
me to make an educated guess as to what the answer might be.

Looking at the options, I get a hit on the keyword 'Illini' in two of them.
One of them is 'llini Union Bookstore' which doesn't make sense to me as the
ticket is for a bus. What would a bus be doing at a bookstore? This prompted
me to choose the option that said 'Illini Union' as it is much more likely to
be the name of a bus stop.